services:
  engine:
    image: ghcr.io/${OWNER:-cpe-4irc-eyjafjallajokull}/app-qg-java-engine:${IMAGE_TAG:-latest}
    container_name: app-qg-java-engine
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_POOL_SIZE=${POSTGRES_POOL_SIZE:-5}
      - POSTGRES_CONNECTION_TIMEOUT_MS=${POSTGRES_CONNECTION_TIMEOUT_MS:-30000}
      - RABBITMQ_URI=${RABBITMQ_URI}
      - RABBITMQ_QUEUE_DURABLE=${RABBITMQ_QUEUE_DURABLE:-true}
      - KEYCLOAK_ISSUER=${KEYCLOAK_ISSUER:-http://localhost:8080/realms/sdmis}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_TIMEOUT_MS=${KEYCLOAK_TIMEOUT_MS:-3000}
      - KEYCLOAK_TOKEN_EXPIRY_SKEW_SECONDS=${KEYCLOAK_TOKEN_EXPIRY_SKEW_SECONDS:-30}
      - SDMIS_API_BASE_URL=${SDMIS_API_BASE_URL:-http://localhost:3001}
      - SDMIS_API_TIMEOUT_MS=${SDMIS_API_TIMEOUT_MS:-5000}
      - DECISION_MAX_DISTANCE_KM=${DECISION_MAX_DISTANCE_KM:-}
      - DECISION_MIN_ENERGY_LEVEL=${DECISION_MIN_ENERGY_LEVEL:-}
    restart: unless-stopped
    networks:
      - databases
      - proxy

networks:
  databases:
    external: true
